import React from 'react';
import LandingPage from '../../components/LandingPage';

export default function PromptGenerator() {
  const meta = {
    title: "Free Prompt Generator | Create Perfect Prompts Instantly",
    description: "The ultimate free prompt generator. Stop guessing what the AI wants and start generating highly specific, optimized prompts for ChatGPT, Claude, and Midjourney.",
    h1: "Free AI Prompt Generator",
    h2_main: "What is a Prompt Generator and Why Do You Need One?",
    targetKeyword: "prompt generator",
    urlPath: "/prompt-generator"
  };

  const content = (
    <>
      <p>
        If you have ever stared at a blinking cursor in ChatGPT, wondering how to ask for exactly what you want, you are not alone. A <strong>prompt generator</strong> is the ultimate solution to the "blank page problem" of the AI era. It acts as a translator between your raw ideas and the highly specific, structured language that large language models (LLMs) understand best.
      </p>

      <h3>The Evolution of Prompt Engineering</h3>
      <p>
        In the early days of AI, users typed simple queries and got simple—often generic or incorrect—answers. Today, AI models are incredibly powerful, but they require precision. A dedicated prompt generator bridges this gap by automatically applying advanced prompt engineering techniques like role-prompting, few-shot learning, and structural formatting.
      </p>
      <p>
        Instead of typing "write a blog post about SEO," a prompt generator expands your idea into a detailed instruction set: defining the persona, the target audience, the tone of voice, formatting constraints, and negative constraints (what *not* to do). This transforms a mediocre output into a professional-grade asset in seconds.
      </p>

      <h3>How PromptQuill's Prompt Generator Works</h3>
      <p>
        PromptQuill was built specifically for founders, developers, and content creators who need high-quality outputs fast. Our free prompt generator uses a multi-step optimization engine:
      </p>
      <ul>
        <li><strong>Intent Recognition:</strong> We analyze your base idea to understand your actual goal.</li>
        <li><strong>Context Expansion:</strong> We automatically add necessary background information and parameters that you might have forgotten to include.</li>
        <li><strong>Framework Application:</strong> Depending on your task, we format the prompt using proven structures like CREATE, PAS (Problem-Agitate-Solve), or RTF (Role-Task-Format).</li>
      </ul>

      <h3>Stop Wasting Time on "Prompt Tweaking"</h3>
      <p>
        The average professional wastes 15-20 minutes a day just tweaking prompts, arguing with the AI, and regenerating responses. By using a standardized prompt generator, you eliminate the trial-and-error phase. You input your core requirement once, and our engine crafts the perfect instruction set on the first try.
      </p>
      <p>
        Whether you are generating code architecture, crafting a marketing email, or building a startup business plan, leveraging a prompt generator ensures you get maximum value from your AI subscriptions.
      </p>
    </>
  );

  const faqs = [
    {
      question: "Is this prompt generator really free?",
      answer: "Yes, PromptQuill offers a generous free tier that allows you to use our prompt generator every day without a credit card. You can upgrade to Pro for unlimited generations."
    },
    {
      question: "Which AI models does this work with?",
      answer: "The prompts generated by our tool are universally optimized for state-of-the-art models including OpenAI's ChatGPT (GPT-4o), Anthropic's Claude 3.5 Sonnet, and Google Gemini."
    },
    {
      question: "Do I need to know prompt engineering to use this?",
      answer: "Not at all. That is the entire purpose of a prompt generator. You provide the basic idea, and our tool handles the complex engineering, formatting, and structuring automatically."
    },
    {
      question: "Can it generate code prompts?",
      answer: "Absolutely. Our Coding Mode specifically formats prompts to ensure AI models output clean, syntax-highlighted, production-ready code with no fluff."
    },
    {
      question: "How long does it take to generate a prompt?",
      answer: "Less than 5 seconds. Our engine is highly optimized to deliver complex, multi-tabbed prompts almost instantly."
    }
  ];

  return <LandingPage meta={meta} content={content} faqs={faqs} />;
}
